config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :employees

get 'home/index'
  # root 'home#index'
  get 'home/about'
  root 'employees#index'
  

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/employee.rb
class Employee < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :employees
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: %i[ show edit update destroy ]

  # GET /employees or /employees.json
  def index
    @employees = Employee.all
  end

  # GET /employees/1 or /employees/1.json
  def show
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees or /employees.json
  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to employee_url(@employee), notice: "Employee was successfully created." }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1 or /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to employee_url(@employee), notice: "Employee was successfully updated." }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1 or /employees/1.json
  def destroy
    @employee.destroy

    respond_to do |format|
      format.html { redirect_to employees_url, notice: "Employee was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def employee_params
      params.require(:employee).permit(:first_name, :last_name, :email, :phone, :twitter, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def about
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/employees/_employee.html.erb
<body style="background-color:lightgrey;box-sizing:border-box;">
<div id="<%= dom_id employee %>">
  <p>
    <strong>First name:</strong>
    <%= employee.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= employee.last_name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= employee.email %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= employee.phone %>
  </p>

  <p>
    <strong>Twitter:</strong>
    <%= employee.twitter %>
  </p>

</div>
</body>

app/views/employees/_form.html.erb
<body style="background-color:lightgrey;box-sizing:border-box;">
<%= form_with(model: employee) do |form| %>
  <% if employee.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
        <% employee.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="table" class="field form-group">
   
    <%= form.text_field :first_name, class:"form-control", placeholder:"First Name" %>
  </div>

  <div class="field form-group">
   
    <%= form.text_field :last_name,  class:"form-control", placeholder:"Last Name"  %>
  </div>

  <div class="field form-group">
   
    <%= form.text_field :email,  class:"form-control", placeholder:"Email"  %>
  </div>

  <div class="field form-group">
  
    <%= form.text_field :phone,  class:"form-control" ,placeholder:"Phone Number" %>
  </div>

  <div >
    
    <%= form.text_field :twitter,  class:"form-control" ,placeholder:"Twitter"  %>
  </div>
    <br />

  <div >
    
    <%= form.number_field :user_id, id: :employee_user_id,  class:"form-control" ,value:current_user.id, type: :hidden  %>
  </div>
  <br />


  <div>
    <%= form.submit class:"btn btn-secondary" %>
  </div>
<% end %>
</body>

app/views/employees/edit.html.erb
<body style="background-color:lightgrey;box-sizing:border-box;">>
<h1>Editing employee</h1>
<br />

<%= render "form", employee: @employee %>

<br>
<br />

<div>
  <%= link_to "Show this employee", @employee, class:"btn btn-secondary" %> 
  <%= link_to "Back to employees", employees_path, class:"btn btn-dark" %>
</div>
<body>

app/views/employees/index.html.erb
 
    <br />
    
<% if user_signed_in? %>



    <br />

<h1 class="table">Employees List</h1>


<div style="background-color: light-grey"  class="table table-striped table-bordered table-hover" id="employees">
 <table class="table">

    <tbody>

    <tr>

  <%   @employees.each do |employee| %>
    <%= render employee %>
    </tr>
    </tbody>
    <p>
    
      <%= link_to "Show this employee", employee %>
      <%# <td><%= link_to 'Show', employee%></td>
    </p>
  <% end %>



<%= link_to "New employee", new_employee_path, class:"btn btn-secondary" %>
<%else%>

<div style="background-color: light-grey">

<h1>Welcome Aboard!&#128512;</h1>

<br />

<div class="text-success" id="timer">
    <%= javascript_pack_tag 'Timer' %>
    </div>
</div>
   <div id="footer">
    <%= javascript_pack_tag 'Footer' %>
    </div>
 
<%end%>

app/views/employees/new.html.erb
<h1>Add New employee</h1>
<br />

<%= render "form", employee: @employee %>

<br>

<div>
  <%= link_to "Back to employees", employees_path, class:"btn btn-dark" %>
</div>

app/views/employees/show.html.erb
 <body style="background-color:lightgrey;box-sizing:border-box;">>
<div class="jumbotron">
  <h1 class="display-4"><%= @employee.first_name%>
  <%= @employee.last_name%></h1>
  <p class="lead"> <%= @employee.email%>
 |  <%= @employee.phone%> |
    <%= @employee.twitter%></p>
    <br />
   <%= link_to "Edit this employee", edit_employee_path(@employee), class:"btn btn-secondary" %> 

  <%= link_to "Back to employees", employees_path, class:"btn btn-dark" %>
 <br/>
</div>

 <%= button_to "Destroy this employee", @employee, method: :delete , class:"btn btn-danger"%>
 </body>

app/views/home/_header.html.erb
<body style="background-color:lightgrey;box-sizing:border-box;">
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
<%= link_to 'Skyline School', root_path, class:"navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
     
  
<%#          
      <li class="nav-item">
      <%= link_to 'Employees', employees_path, class:"nav-link"%>
       
      </li> %>
       
          <li class="nav-item">
      <%= link_to 'About Us', home_about_path, class:"nav-link"%>
      </li>
      </li>
      <% if user_signed_in? %>
        <li class="nav-item">
      <%= link_to 'Add Employee', new_employee_path, class:"nav-link"%>
       
      </li>
         <li class="nav-item">
      <%# <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class:"nav-link" %> 
      <%= link_to 'Sign Out', destroy_user_session_path, class: "nav-link", data: { turbo_method: :delete } %>
  
     
       
      </li>
        <li class="nav-item">
      <%= link_to 'Edit Profile', edit_user_registration_path, class:"nav-link"%>
     
      <%else%>
        <li class="nav-item">
      <%= link_to 'Sign Up', new_user_registration_path, class:"nav-link"%>
       
      </li>
        <li class="nav-item">
      <%= link_to 'Sign in', new_user_session_path, class:"nav-link"%>
       
      </li>
      <%end%>
     
      
  
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>
</body>

app/views/home/about.html.erb
<body style="background-color:lightgrey;box-sizing:border-box;">
<div id="container">
<h1>About us</h1>
<p>Skyline School Muguga is an international high school located on the outskirts of Nairobi. Our main objective, to help grow powerful global citizens</p>
<ul>
<li >Contact us : 01123748499</li>
<li  >Email: skylineschool@gmail.com</li>
<li >Twitter : @skylineschool</li>
<li  >Instagram : @skyline_school</li>
</ul>
</div>
</div>
</body>

app/views/home/index.html.erb
<h1>Welcome Aboard!</h1>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
 <%= notice%>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

 <title>Employees system</title>
 <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
   
  </head>
  <body>
    <%= render 'home/header' %>
  <div class='container'>
  <br />
  <% if notice%>
  <%= render 'layouts/alerts'%>
  <% end %>
  <br />
      <%= yield %>
      </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>